export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const SET_FORGET_PASSWORD = "SET_FORGET_PASSWORD";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
export const GET_ALL_COMMENT = "GET_ALL_COMMENT";
export const GET_ALL_COMMENT_FAIL = "GET_ALL_COMMENT_FAIL";
export const GET_COMMENTBYID_PASS = "GET_COMMENTBYID_PASS";
export const GET_COMMENTBYID_FAIL = "GET_COMMENTBYID_FAIL";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_FAILURE = "ADD_REPLY_FAILURE";
export const UPDATE_COMMENT_PASS = "UPDATE_COMMENT_PASS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";
export const DELETE_COMMENT_PASS = "DELETE_COMMENT_PASS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const GET_REPLYBYID_PASS = "GET_REPLYBYID_PASS";
export const GET_REPLYBYID_FAIL = "GET_REPLYBYID_FAIL";
export const UPDATE_REPLY_PASS = "UPDATE_REPLY_PASS";
export const UPDATE_REPLY_FAIL = "UPDATE_REPLY_FAIL";
export const GETSELECTED_REPLY_PASS = "GETSELECTED_REPLY_PASS";
export const GETSELECTED_REPLY_FAIL = "GETSELECTED_REPLY_FAIL";
export const DELETE_SELECTED_REPLY_PASS = "DELETE_SELECTED_REPLY_PASS";
export const DELETE_SELECTED_REPLY_FAIL = "DELETE_SELECTED_REPLY_FAIL";
 export const DELETE_ITEM_START="DELETE_ITEM_START";
 export const DELETE_ITEM_SUCCESS="DELETE_ITEM_SUCCESS";
 export const DELETE_ITEM_FAILURE="DELETE_ITEM_FAILURE";



export const  UPDATE_COUNT_DATA = "UPDATE_COUNT_DATA";
export const  GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const  GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const  GET_ALLVIDEO_SUCCESS = "GET_ALLVIDEO_SUCCESS";
export const  GET_ALLVIDEO_FAIL = "GET_ALLVIDEO_FAIL";

export const  UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL";
export const  UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";

export const  GET_SINGLE_VIDEO_SUCCESS = "GET_SINGLE_VIDEO_SUCCESS";
export const  GET_SINGLE_VIDEO_FAIL = "GET_SINGLE_VIDEO_FAIL";

export const  GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";
export const  GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORYBYID_SUCCESS="GET_CATEGORYBYID_SUCCESS";
export const GET_CATEGORYBYID_FAIL = "GET_CATEGORYBYID_FAIL";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";